"""Financial backtest for the composite risk score.

This script evaluates how much observed claim exposure the action policy would
have put in front of facility teams during the holdout period. Savings are
estimated from an explicit uniform intervention-effectiveness scenario.
"""

from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import polars as pl

from modeling.business_policy import (
    DEFAULT_ALERT_REVIEW_COST,
    DEFAULT_CAPACITY_RATES,
    DEFAULT_INTERVENTION_EFFECTIVENESS,
    EVENT_LABELS,
    INTERVENTION_EFFECTIVENESS_SENSITIVITY,
    PolicyAssumptions,
)
from modeling.outcome_costs import build_actual_event_table
from modeling.score_composite import DEFAULT_OUTPUT, build_composite_scores


ARTIFACTS_DIR = ROOT / "modeling" / "artifacts"
DOCS_DIR = ROOT / "docs"
SUMMARY_PATH = ARTIFACTS_DIR / "financial_backtest_summary.csv"
BY_TYPE_PATH = ARTIFACTS_DIR / "financial_backtest_by_incident_type.csv"
CAPTURED_EVENTS_PATH = ARTIFACTS_DIR / "financial_backtest_captured_events.csv"
EFFECTIVENESS_SENSITIVITY_PATH = ARTIFACTS_DIR / "financial_effectiveness_sensitivity.csv"
REPORT_PATH = DOCS_DIR / "backtest-results.md"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run a composite-score financial backtest.")
    parser.add_argument(
        "--scores-path",
        default=str(DEFAULT_OUTPUT),
        help="Composite scores parquet generated by modeling/score_composite.py.",
    )
    parser.add_argument(
        "--score-if-missing",
        action="store_true",
        help="Build composite scores first if the scores parquet does not exist.",
    )
    parser.add_argument(
        "--alert-cost",
        type=float,
        default=DEFAULT_ALERT_REVIEW_COST,
        help="Assumed operational cost per alert/intervention review.",
    )
    parser.add_argument(
        "--intervention-effectiveness",
        type=float,
        default=DEFAULT_INTERVENTION_EFFECTIVENESS,
        help="Uniform baseline intervention effectiveness applied to all incident types.",
    )
    parser.add_argument(
        "--effectiveness-sensitivity",
        type=float,
        nargs="+",
        default=list(INTERVENTION_EFFECTIVENESS_SENSITIVITY),
        help="Uniform effectiveness rates to evaluate in sensitivity analysis.",
    )
    return parser.parse_args()


def _fmt_money(value: float) -> str:
    if value < 0:
        return f"-${abs(value):,.0f}"
    return f"${value:,.0f}"


def _fmt_pct(value: float) -> str:
    return f"{value:.1%}"


def _sum(df: pl.DataFrame, column: str) -> float:
    if df.is_empty() or column not in df.columns:
        return 0.0
    value = df[column].sum()
    return float(value) if value is not None else 0.0


def _min(df: pl.DataFrame, column: str) -> float:
    if df.is_empty() or column not in df.columns:
        return 0.0
    value = df[column].min()
    return float(value) if value is not None else 0.0


def _median(df: pl.DataFrame, column: str) -> float:
    if df.is_empty() or column not in df.columns:
        return 0.0
    value = df[column].median()
    return float(value) if value is not None else 0.0


def load_scores(path: Path, score_if_missing: bool) -> pl.DataFrame:
    if not path.exists():
        if not score_if_missing:
            raise FileNotFoundError(
                f"{path} does not exist. Run modeling/score_composite.py first "
                "or pass --score-if-missing."
            )
        scored = build_composite_scores()
        path.parent.mkdir(parents=True, exist_ok=True)
        scored.write_parquet(path)

    return pl.read_parquet(path)


def select_top_by_facility(scores: pl.DataFrame, capacity_rate: float) -> pl.DataFrame:
    selected = []
    for group in scores.partition_by("facility_id", maintain_order=True):
        n_select = max(1, int(math.ceil(group.height * capacity_rate)))
        selected.append(group.sort("composite_expected_cost", descending=True).head(n_select))
    return pl.concat(selected, how="vertical") if selected else scores.head(0)


def policy_alerts(
    scores: pl.DataFrame,
    assumptions: PolicyAssumptions,
) -> dict[str, pl.DataFrame]:
    alerts = {}
    for rate in assumptions.capacity_rates:
        label = f"top_{int(rate * 100):02d}pct_per_facility"
        alerts[label] = select_top_by_facility(scores, rate)
    alerts["economic_threshold"] = scores.filter(
        pl.col("composite_expected_cost") * assumptions.intervention_effectiveness
        >= assumptions.alert_review_cost
    )
    return alerts


def _empty_captured_events(events: pl.DataFrame) -> pl.DataFrame:
    schema = dict(events.schema)
    schema.update(
        {
            "score_id": pl.UInt32,
            "composite_expected_cost": pl.Float64,
            "expected_avoidable_cost": pl.Float64,
            "top_reason": pl.Utf8,
            "reason_codes": pl.Utf8,
            "alert_window_start": pl.Datetime("us"),
        }
    )
    return pl.DataFrame(schema=schema)


def captured_events(alerts: pl.DataFrame, events: pl.DataFrame) -> pl.DataFrame:
    if alerts.is_empty() or events.is_empty():
        return _empty_captured_events(events)

    candidate = (
        alerts.select(
            [
                "score_id",
                "resident_id",
                "facility_id",
                "window_start",
                "composite_expected_cost",
                "expected_avoidable_cost",
                "top_reason",
                "reason_codes",
            ]
        )
        .join(events, on="resident_id", how="inner", suffix="_event")
        .with_columns(
            capture_end=pl.col("window_start")
            + pl.duration(days=pl.col("horizon_days"))
        )
        .filter(
            (pl.col("event_time") >= pl.col("window_start"))
            & (pl.col("event_time") < pl.col("capture_end"))
        )
        .sort(["event_id", "event_type", "window_start"])
        .unique(["event_id", "event_type"], keep="first", maintain_order=True)
        .rename({"window_start": "alert_window_start"})
        .drop("capture_end")
    )
    return candidate


def summarize_policy(
    policy_name: str,
    scores: pl.DataFrame,
    alerts: pl.DataFrame,
    events: pl.DataFrame,
    assumptions: PolicyAssumptions,
) -> tuple[dict[str, float], pl.DataFrame]:
    captured = captured_events(alerts, events).with_columns(
        pl.lit(assumptions.intervention_effectiveness).alias("intervention_effectiveness"),
        (pl.col("claim_cost") * assumptions.intervention_effectiveness).alias(
            "estimated_avoided_claim_cost"
        ),
        pl.lit(assumptions.intervention_effectiveness).alias("estimated_prevented_events"),
    )

    intervention_cost = alerts.height * assumptions.alert_review_cost
    captured_claim_cost = _sum(captured, "claim_cost")
    avoided_claim_cost = _sum(captured, "estimated_avoided_claim_cost")
    total_claim_cost = _sum(events, "claim_cost")
    net_savings = avoided_claim_cost - intervention_cost

    summary = {
        "policy": policy_name,
        "scored_windows": scores.height,
        "alerts": alerts.height,
        "alert_rate": alerts.height / scores.height if scores.height else 0.0,
        "alerted_residents": alerts["resident_id"].n_unique() if alerts.height else 0,
        "threshold_min_composite_expected_cost": _min(alerts, "composite_expected_cost"),
        "threshold_median_composite_expected_cost": _median(
            alerts, "composite_expected_cost"
        ),
        "expected_claim_cost_alerted": _sum(alerts, "composite_expected_cost"),
        "expected_avoidable_cost_alerted": _sum(alerts, "composite_expected_cost")
        * assumptions.intervention_effectiveness,
        "actual_events": events.height,
        "actual_claim_cost": total_claim_cost,
        "captured_events": captured.height,
        "captured_claim_cost": captured_claim_cost,
        "claim_cost_capture_rate": captured_claim_cost / total_claim_cost
        if total_claim_cost
        else 0.0,
        "estimated_prevented_events": _sum(captured, "estimated_prevented_events"),
        "estimated_avoided_claim_cost": avoided_claim_cost,
        "intervention_cost": intervention_cost,
        "estimated_net_savings": net_savings,
        "estimated_roi": net_savings / intervention_cost if intervention_cost else 0.0,
        "intervention_effectiveness": assumptions.intervention_effectiveness,
    }
    return summary, captured.with_columns(pl.lit(policy_name).alias("policy"))


def _empty_by_type() -> pl.DataFrame:
    return pl.DataFrame(
        schema={
            "policy": pl.Utf8,
            "event_type": pl.Utf8,
            "actual_events": pl.UInt32,
            "actual_claim_cost": pl.Float64,
            "captured_events": pl.UInt32,
            "captured_claim_cost": pl.Float64,
            "event_capture_rate": pl.Float64,
            "claim_cost_capture_rate": pl.Float64,
            "estimated_avoided_claim_cost": pl.Float64,
        }
    )


def summarize_by_type(events: pl.DataFrame, captured_all: pl.DataFrame) -> pl.DataFrame:
    if events.is_empty():
        return _empty_by_type()

    total = events.group_by("event_type").agg(
        pl.len().alias("actual_events"),
        pl.col("claim_cost").sum().alias("actual_claim_cost"),
    )

    if captured_all.is_empty():
        policies = ["none"]
        captured = pl.DataFrame(
            schema={
                "policy": pl.Utf8,
                "event_type": pl.Utf8,
                "captured_events": pl.UInt32,
                "captured_claim_cost": pl.Float64,
                "estimated_avoided_claim_cost": pl.Float64,
            }
        )
    else:
        captured = captured_all.group_by(["policy", "event_type"]).agg(
            pl.len().alias("captured_events"),
            pl.col("claim_cost").sum().alias("captured_claim_cost"),
            pl.col("estimated_avoided_claim_cost")
            .sum()
            .alias("estimated_avoided_claim_cost"),
        )
        policies = captured["policy"].unique().to_list()

    rows = []
    fill_cols = [
        "captured_events",
        "captured_claim_cost",
        "estimated_avoided_claim_cost",
    ]
    for policy in policies:
        policy_captured = captured.filter(pl.col("policy") == policy).drop(
            "policy", strict=False
        )
        merged = (
            total.join(policy_captured, on="event_type", how="left")
            .with_columns(pl.lit(policy).alias("policy"))
            .with_columns([pl.col(c).fill_null(0) for c in fill_cols])
            .with_columns(
                event_capture_rate=pl.col("captured_events") / pl.col("actual_events"),
                claim_cost_capture_rate=pl.col("captured_claim_cost")
                / pl.col("actual_claim_cost"),
            )
        )
        rows.append(merged)

    return pl.concat(rows, how="vertical").select(
        [
            "policy",
            "event_type",
            "actual_events",
            "actual_claim_cost",
            "captured_events",
            "captured_claim_cost",
            "event_capture_rate",
            "claim_cost_capture_rate",
            "estimated_avoided_claim_cost",
        ]
    )


def write_report(
    summary: pl.DataFrame,
    by_type: pl.DataFrame,
    scores: pl.DataFrame,
    assumptions: PolicyAssumptions,
    effectiveness_sensitivity: pl.DataFrame,
) -> None:
    primary_policy = "top_10pct_per_facility"
    primary = summary.filter(pl.col("policy") == primary_policy)
    if primary.is_empty():
        primary = summary.head(1)
    row = primary.row(0, named=True)

    primary_by_type = (
        by_type.filter(pl.col("policy") == row["policy"])
        .with_columns(pl.col("event_type").replace(EVENT_LABELS).alias("label"))
    )

    lines = [
        "# Composite Risk Score Backtest Results",
        "",
        "For the full technical modeling strategy behind these results, see",
        "`docs/modeling-strategy.md`.",
        "",
        f"Scoring period: {scores['window_start'].min().date()} to {scores['window_end'].max().date()}",
        "",
        "The backtest estimates financial value by asking which observed holdout events",
        "would have been preceded by an alert. Estimated savings apply one uniform",
        "scenario assumption for intervention effectiveness, defined in",
        "`modeling/business_policy.py`.",
        "",
        f"Baseline intervention effectiveness: {_fmt_pct(assumptions.intervention_effectiveness)}",
        "",
        "## Primary Policy",
        "",
        f"Policy: `{row['policy']}`",
        "",
        f"- Alerts: {int(row['alerts']):,} of {int(row['scored_windows']):,} scored windows ({_fmt_pct(row['alert_rate'])})",
        f"- Actual claim exposure captured: {_fmt_money(row['captured_claim_cost'])} of {_fmt_money(row['actual_claim_cost'])} ({_fmt_pct(row['claim_cost_capture_rate'])})",
        f"- Estimated avoided claim dollars: {_fmt_money(row['estimated_avoided_claim_cost'])}",
        f"- Intervention cost: {_fmt_money(row['intervention_cost'])}",
        f"- Estimated net savings: {_fmt_money(row['estimated_net_savings'])}",
        f"- Estimated ROI: {row['estimated_roi']:.2f}x",
        "",
        "## Sensitivity",
        "",
        "### Policy Sensitivity",
        "",
        "| Policy | Alerts | Captured claim cost | Avoided claim cost | Intervention cost | Net savings | ROI |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]

    for s in summary.iter_rows(named=True):
        lines.append(
            f"| `{s['policy']}` | {int(s['alerts']):,} | "
            f"{_fmt_money(s['captured_claim_cost'])} | "
            f"{_fmt_money(s['estimated_avoided_claim_cost'])} | "
            f"{_fmt_money(s['intervention_cost'])} | "
            f"{_fmt_money(s['estimated_net_savings'])} | "
            f"{s['estimated_roi']:.2f}x |"
        )

    primary_effectiveness = effectiveness_sensitivity.filter(
        pl.col("policy") == row["policy"]
    )
    lines.extend(
        [
            "",
            "### Primary Policy Effectiveness Sensitivity",
            "",
            "| Assumed effectiveness | Alerts | Captured claim cost | Avoided claim cost | Intervention cost | Net savings | ROI |",
            "|---:|---:|---:|---:|---:|---:|---:|",
        ]
    )
    for s in primary_effectiveness.sort("intervention_effectiveness").iter_rows(named=True):
        lines.append(
            f"| {_fmt_pct(s['intervention_effectiveness'])} | "
            f"{int(s['alerts']):,} | "
            f"{_fmt_money(s['captured_claim_cost'])} | "
            f"{_fmt_money(s['estimated_avoided_claim_cost'])} | "
            f"{_fmt_money(s['intervention_cost'])} | "
            f"{_fmt_money(s['estimated_net_savings'])} | "
            f"{s['estimated_roi']:.2f}x |"
        )

    lines.extend(
        [
            "",
            "## Primary Policy By Incident Type",
            "",
            "| Incident type | Actual events | Captured events | Captured claim cost | Capture rate |",
            "|---|---:|---:|---:|---:|",
        ]
    )
    for s in primary_by_type.sort("actual_claim_cost", descending=True).iter_rows(named=True):
        lines.append(
            f"| {s['label']} | {int(s['actual_events']):,} | "
            f"{int(s['captured_events']):,} | {_fmt_money(s['captured_claim_cost'])} | "
            f"{_fmt_pct(s['claim_cost_capture_rate'])} |"
        )

    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "These are backtested financial indicators, not causal proof. The strongest",
            "observed metric is captured claim exposure: dollars from events that had an",
            "alert before they occurred. Net savings depends on intervention cost and",
            "the uniform effectiveness scenario, which should be replaced with measured",
            "effects from a prospective pilot.",
            "",
        ]
    )

    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")


def load_events_for_scores(scores: pl.DataFrame) -> pl.DataFrame:
    event_start = scores["window_start"].min()
    event_end = scores["window_end"].max()
    return build_actual_event_table(start=event_start, end=event_end)


def run_backtest(
    scores: pl.DataFrame,
    assumptions: PolicyAssumptions,
    events: pl.DataFrame | None = None,
) -> tuple[pl.DataFrame, pl.DataFrame, pl.DataFrame]:
    if events is None:
        events = load_events_for_scores(scores)

    summaries = []
    captured_frames = []
    for policy_name, alerts in policy_alerts(scores, assumptions).items():
        summary, captured = summarize_policy(
            policy_name, scores, alerts, events, assumptions
        )
        summaries.append(summary)
        if not captured.is_empty():
            captured_frames.append(captured)

    summary_df = pl.DataFrame(summaries)
    captured_all = (
        pl.concat(captured_frames, how="vertical") if captured_frames else _empty_captured_events(events)
    )
    by_type = summarize_by_type(events, captured_all)
    return summary_df, by_type, captured_all


def run_effectiveness_sensitivity(
    scores: pl.DataFrame,
    alert_review_cost: float,
    rates: tuple[float, ...],
    events: pl.DataFrame,
) -> pl.DataFrame:
    frames = []
    for rate in rates:
        assumptions = PolicyAssumptions(
            alert_review_cost=alert_review_cost,
            intervention_effectiveness=rate,
            effectiveness_sensitivity=rates,
        )
        summary, _, _ = run_backtest(scores, assumptions, events)
        frames.append(summary)
    return pl.concat(frames, how="vertical")


def main() -> None:
    args = parse_args()
    sensitivity_rates = tuple(args.effectiveness_sensitivity)
    if args.intervention_effectiveness not in sensitivity_rates:
        sensitivity_rates = tuple(
            sorted((*sensitivity_rates, args.intervention_effectiveness))
        )

    assumptions = PolicyAssumptions(
        alert_review_cost=args.alert_cost,
        intervention_effectiveness=args.intervention_effectiveness,
        effectiveness_sensitivity=sensitivity_rates,
    )
    ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)

    scores = load_scores(Path(args.scores_path), args.score_if_missing)
    events = load_events_for_scores(scores)
    summary, by_type, captured = run_backtest(scores, assumptions, events)
    effectiveness_sensitivity = run_effectiveness_sensitivity(
        scores,
        assumptions.alert_review_cost,
        assumptions.effectiveness_sensitivity,
        events,
    )

    summary.write_csv(SUMMARY_PATH)
    by_type.write_csv(BY_TYPE_PATH)
    captured.write_csv(CAPTURED_EVENTS_PATH)
    effectiveness_sensitivity.write_csv(EFFECTIVENESS_SENSITIVITY_PATH)
    write_report(summary, by_type, scores, assumptions, effectiveness_sensitivity)

    primary = summary.filter(pl.col("policy") == "top_10pct_per_facility").row(
        0, named=True
    )
    print("\nFinancial backtest complete.")
    print(f"  Summary: {SUMMARY_PATH}")
    print(f"  By type: {BY_TYPE_PATH}")
    print(f"  Effectiveness sensitivity: {EFFECTIVENESS_SENSITIVITY_PATH}")
    print(f"  Report: {REPORT_PATH}")
    print(
        "  Primary policy net savings: "
        f"{_fmt_money(primary['estimated_net_savings'])} "
        f"({primary['estimated_roi']:.2f}x ROI)"
    )


if __name__ == "__main__":
    main()
