"""Financial backtest for the composite risk score.

This script evaluates how much observed claim exposure the action policy would
have put in front of facility teams during the holdout period. Savings are
estimated from an explicit uniform intervention-effectiveness scenario.
"""

from __future__ import annotations

import argparse
import math
import sys
from datetime import timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import pandas as pd
import polars as pl

from modeling.business_policy import (
    DEFAULT_INTERVENTION_EFFECTIVENESS,
    DEFAULT_ALERT_REVIEW_COST,
    DEFAULT_CAPACITY_RATES,
    EVENT_LABELS,
    INTERVENTION_EFFECTIVENESS_SENSITIVITY,
    PolicyAssumptions,
)
from modeling.outcome_costs import build_actual_event_table
from modeling.score_composite import DEFAULT_OUTPUT, build_composite_scores


ARTIFACTS_DIR = ROOT / "modeling" / "artifacts"
DOCS_DIR = ROOT / "docs"
SUMMARY_PATH = ARTIFACTS_DIR / "financial_backtest_summary.csv"
BY_TYPE_PATH = ARTIFACTS_DIR / "financial_backtest_by_incident_type.csv"
CAPTURED_EVENTS_PATH = ARTIFACTS_DIR / "financial_backtest_captured_events.csv"
EFFECTIVENESS_SENSITIVITY_PATH = ARTIFACTS_DIR / "financial_effectiveness_sensitivity.csv"
REPORT_PATH = DOCS_DIR / "backtest-results.md"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run a composite-score financial backtest.")
    parser.add_argument(
        "--scores-path",
        default=str(DEFAULT_OUTPUT),
        help="Composite scores parquet generated by modeling/score_composite.py.",
    )
    parser.add_argument(
        "--score-if-missing",
        action="store_true",
        help="Build composite scores first if the scores parquet does not exist.",
    )
    parser.add_argument(
        "--alert-cost",
        type=float,
        default=DEFAULT_ALERT_REVIEW_COST,
        help="Assumed operational cost per alert/intervention review.",
    )
    parser.add_argument(
        "--intervention-effectiveness",
        type=float,
        default=DEFAULT_INTERVENTION_EFFECTIVENESS,
        help="Uniform baseline intervention effectiveness applied to all incident types.",
    )
    parser.add_argument(
        "--effectiveness-sensitivity",
        type=float,
        nargs="+",
        default=list(INTERVENTION_EFFECTIVENESS_SENSITIVITY),
        help="Uniform effectiveness rates to evaluate in sensitivity analysis.",
    )
    return parser.parse_args()


def _fmt_money(value: float) -> str:
    if value < 0:
        return f"-${abs(value):,.0f}"
    return f"${value:,.0f}"


def _fmt_pct(value: float) -> str:
    return f"{value:.1%}"


def load_scores(path: Path, score_if_missing: bool) -> pd.DataFrame:
    if not path.exists():
        if not score_if_missing:
            raise FileNotFoundError(
                f"{path} does not exist. Run modeling/score_composite.py first "
                "or pass --score-if-missing."
            )
        scored = build_composite_scores()
        path.parent.mkdir(parents=True, exist_ok=True)
        scored.write_parquet(path)

    scores = pl.read_parquet(path).to_pandas()
    for col in ["window_start", "window_end", "feature_cutoff"]:
        scores[col] = pd.to_datetime(scores[col])
    return scores


def select_top_by_facility(scores: pd.DataFrame, capacity_rate: float) -> pd.Series:
    selected = pd.Series(False, index=scores.index)
    for _, group in scores.groupby("facility_id", sort=False):
        n_select = max(1, int(math.ceil(len(group) * capacity_rate)))
        chosen = group.sort_values("composite_expected_cost", ascending=False).head(n_select)
        selected.loc[chosen.index] = True
    return selected


def policy_masks(scores: pd.DataFrame, assumptions: PolicyAssumptions) -> dict[str, pd.Series]:
    masks = {}
    for rate in assumptions.capacity_rates:
        label = f"top_{int(rate * 100):02d}pct_per_facility"
        masks[label] = select_top_by_facility(scores, rate)
    masks["economic_threshold"] = (
        scores["composite_expected_cost"] * assumptions.intervention_effectiveness
        >= assumptions.alert_review_cost
    )
    return masks


def captured_events(alerts: pd.DataFrame, events: pd.DataFrame) -> pd.DataFrame:
    if alerts.empty or events.empty:
        return pd.DataFrame(columns=list(events.columns) + ["score_id", "alert_window_start"])

    candidate = alerts[
        [
            "score_id",
            "resident_id",
            "facility_id",
            "window_start",
            "composite_expected_cost",
            "expected_avoidable_cost",
            "top_reason",
            "reason_codes",
        ]
    ].merge(events, on="resident_id", how="inner", suffixes=("_alert", "_event"))

    candidate["capture_end"] = candidate.apply(
        lambda row: row["window_start"] + timedelta(days=int(row["horizon_days"])),
        axis=1,
    )
    candidate = candidate[
        (candidate["event_time"] >= candidate["window_start"])
        & (candidate["event_time"] < candidate["capture_end"])
    ].copy()

    if candidate.empty:
        return candidate

    candidate = candidate.sort_values(["event_id", "event_type", "window_start"])
    candidate = candidate.drop_duplicates(["event_id", "event_type"], keep="first")
    candidate = candidate.rename(columns={"window_start": "alert_window_start"})
    return candidate


def summarize_policy(
    policy_name: str,
    scores: pd.DataFrame,
    selected: pd.Series,
    events: pd.DataFrame,
    assumptions: PolicyAssumptions,
) -> tuple[dict[str, float], pd.DataFrame]:
    alerts = scores[selected].copy()
    captured = captured_events(alerts, events)

    if not captured.empty:
        captured["intervention_effectiveness"] = assumptions.intervention_effectiveness
        captured["estimated_avoided_claim_cost"] = (
            captured["claim_cost"] * assumptions.intervention_effectiveness
        )
        captured["estimated_prevented_events"] = assumptions.intervention_effectiveness
    else:
        captured["intervention_effectiveness"] = []
        captured["estimated_avoided_claim_cost"] = []
        captured["estimated_prevented_events"] = []

    intervention_cost = len(alerts) * assumptions.alert_review_cost
    captured_claim_cost = float(captured["claim_cost"].sum()) if not captured.empty else 0.0
    avoided_claim_cost = (
        float(captured["estimated_avoided_claim_cost"].sum()) if not captured.empty else 0.0
    )
    total_claim_cost = float(events["claim_cost"].sum()) if not events.empty else 0.0
    net_savings = avoided_claim_cost - intervention_cost

    if len(alerts) > 0:
        min_threshold = float(alerts["composite_expected_cost"].min())
        median_threshold = float(alerts["composite_expected_cost"].median())
    else:
        min_threshold = 0.0
        median_threshold = 0.0

    summary = {
        "policy": policy_name,
        "scored_windows": len(scores),
        "alerts": len(alerts),
        "alert_rate": len(alerts) / len(scores) if len(scores) else 0.0,
        "alerted_residents": alerts["resident_id"].nunique() if len(alerts) else 0,
        "threshold_min_composite_expected_cost": min_threshold,
        "threshold_median_composite_expected_cost": median_threshold,
        "expected_claim_cost_alerted": float(alerts["composite_expected_cost"].sum()),
        "expected_avoidable_cost_alerted": float(
            alerts["composite_expected_cost"].sum() * assumptions.intervention_effectiveness
        ),
        "actual_events": len(events),
        "actual_claim_cost": total_claim_cost,
        "captured_events": len(captured),
        "captured_claim_cost": captured_claim_cost,
        "claim_cost_capture_rate": captured_claim_cost / total_claim_cost
        if total_claim_cost
        else 0.0,
        "estimated_prevented_events": float(captured["estimated_prevented_events"].sum())
        if not captured.empty
        else 0.0,
        "estimated_avoided_claim_cost": avoided_claim_cost,
        "intervention_cost": intervention_cost,
        "estimated_net_savings": net_savings,
        "estimated_roi": net_savings / intervention_cost if intervention_cost else 0.0,
        "intervention_effectiveness": assumptions.intervention_effectiveness,
    }
    captured["policy"] = policy_name
    return summary, captured


def summarize_by_type(events: pd.DataFrame, captured_all: pd.DataFrame) -> pd.DataFrame:
    total = (
        events.groupby("event_type")
        .agg(actual_events=("event_id", "count"), actual_claim_cost=("claim_cost", "sum"))
        .reset_index()
    )
    if captured_all.empty:
        captured = pd.DataFrame(
            columns=[
                "policy",
                "event_type",
                "captured_events",
                "captured_claim_cost",
                "estimated_avoided_claim_cost",
            ]
        )
    else:
        captured = (
            captured_all.groupby(["policy", "event_type"])
            .agg(
                captured_events=("event_id", "count"),
                captured_claim_cost=("claim_cost", "sum"),
                estimated_avoided_claim_cost=("estimated_avoided_claim_cost", "sum"),
            )
            .reset_index()
        )

    rows = []
    policies = captured["policy"].unique().tolist()
    if not policies:
        policies = ["none"]

    for policy in policies:
        policy_captured = captured[captured["policy"] == policy]
        merged = total.merge(policy_captured, on="event_type", how="left")
        merged["policy"] = policy
        merged[
            ["captured_events", "captured_claim_cost", "estimated_avoided_claim_cost"]
        ] = merged[
            ["captured_events", "captured_claim_cost", "estimated_avoided_claim_cost"]
        ].fillna(0)
        merged["event_capture_rate"] = merged["captured_events"] / merged["actual_events"]
        merged["claim_cost_capture_rate"] = (
            merged["captured_claim_cost"] / merged["actual_claim_cost"]
        )
        rows.append(merged)

    return pd.concat(rows, ignore_index=True)[
        [
            "policy",
            "event_type",
            "actual_events",
            "actual_claim_cost",
            "captured_events",
            "captured_claim_cost",
            "event_capture_rate",
            "claim_cost_capture_rate",
            "estimated_avoided_claim_cost",
        ]
    ]


def write_report(
    summary: pd.DataFrame,
    by_type: pd.DataFrame,
    scores: pd.DataFrame,
    assumptions: PolicyAssumptions,
    effectiveness_sensitivity: pd.DataFrame,
) -> None:
    primary_policy = "top_10pct_per_facility"
    primary = summary[summary["policy"] == primary_policy]
    if primary.empty:
        primary = summary.iloc[[0]]
    row = primary.iloc[0]

    primary_by_type = by_type[by_type["policy"] == row["policy"]].copy()
    primary_by_type["label"] = primary_by_type["event_type"].map(EVENT_LABELS)

    lines = [
        "# Composite Risk Score Backtest Results",
        "",
        "For the full technical modeling strategy behind these results, see",
        "`docs/modeling-strategy.md`.",
        "",
        f"Scoring period: {scores['window_start'].min().date()} to {scores['window_end'].max().date()}",
        "",
        "The backtest estimates financial value by asking which observed holdout events",
        "would have been preceded by an alert. Estimated savings apply one uniform",
        "scenario assumption for intervention effectiveness, defined in",
        "`modeling/business_policy.py`.",
        "",
        f"Baseline intervention effectiveness: {_fmt_pct(assumptions.intervention_effectiveness)}",
        "",
        "## Primary Policy",
        "",
        f"Policy: `{row['policy']}`",
        "",
        f"- Alerts: {int(row['alerts']):,} of {int(row['scored_windows']):,} scored windows ({_fmt_pct(row['alert_rate'])})",
        f"- Actual claim exposure captured: {_fmt_money(row['captured_claim_cost'])} of {_fmt_money(row['actual_claim_cost'])} ({_fmt_pct(row['claim_cost_capture_rate'])})",
        f"- Estimated avoided claim dollars: {_fmt_money(row['estimated_avoided_claim_cost'])}",
        f"- Intervention cost: {_fmt_money(row['intervention_cost'])}",
        f"- Estimated net savings: {_fmt_money(row['estimated_net_savings'])}",
        f"- Estimated ROI: {row['estimated_roi']:.2f}x",
        "",
        "## Sensitivity",
        "",
        "### Policy Sensitivity",
        "",
        "| Policy | Alerts | Captured claim cost | Avoided claim cost | Intervention cost | Net savings | ROI |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]

    for _, s in summary.iterrows():
        lines.append(
            f"| `{s['policy']}` | {int(s['alerts']):,} | "
            f"{_fmt_money(s['captured_claim_cost'])} | "
            f"{_fmt_money(s['estimated_avoided_claim_cost'])} | "
            f"{_fmt_money(s['intervention_cost'])} | "
            f"{_fmt_money(s['estimated_net_savings'])} | "
            f"{s['estimated_roi']:.2f}x |"
        )

    primary_effectiveness = effectiveness_sensitivity[
        effectiveness_sensitivity["policy"] == row["policy"]
    ].copy()
    lines.extend(
        [
            "",
            "### Primary Policy Effectiveness Sensitivity",
            "",
            "| Assumed effectiveness | Alerts | Captured claim cost | Avoided claim cost | Intervention cost | Net savings | ROI |",
            "|---:|---:|---:|---:|---:|---:|---:|",
        ]
    )
    for _, s in primary_effectiveness.sort_values("intervention_effectiveness").iterrows():
        lines.append(
            f"| {_fmt_pct(s['intervention_effectiveness'])} | "
            f"{int(s['alerts']):,} | "
            f"{_fmt_money(s['captured_claim_cost'])} | "
            f"{_fmt_money(s['estimated_avoided_claim_cost'])} | "
            f"{_fmt_money(s['intervention_cost'])} | "
            f"{_fmt_money(s['estimated_net_savings'])} | "
            f"{s['estimated_roi']:.2f}x |"
        )

    lines.extend(
        [
            "",
            "## Primary Policy By Incident Type",
            "",
            "| Incident type | Actual events | Captured events | Captured claim cost | Capture rate |",
            "|---|---:|---:|---:|---:|",
        ]
    )
    for _, s in primary_by_type.sort_values("actual_claim_cost", ascending=False).iterrows():
        lines.append(
            f"| {s['label']} | {int(s['actual_events']):,} | "
            f"{int(s['captured_events']):,} | {_fmt_money(s['captured_claim_cost'])} | "
            f"{_fmt_pct(s['claim_cost_capture_rate'])} |"
        )

    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "These are backtested financial indicators, not causal proof. The strongest",
            "observed metric is captured claim exposure: dollars from events that had an",
            "alert before they occurred. Net savings depends on intervention cost and",
            "the uniform effectiveness scenario, which should be replaced with measured",
            "effects from a prospective pilot.",
            "",
        ]
    )

    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")


def load_events_for_scores(scores: pd.DataFrame) -> pd.DataFrame:
    event_start = scores["window_start"].min()
    event_end = scores["window_end"].max()
    events = build_actual_event_table(start=event_start, end=event_end).to_pandas()
    if not events.empty:
        events["event_time"] = pd.to_datetime(events["event_time"])
    return events


def run_backtest(
    scores: pd.DataFrame,
    assumptions: PolicyAssumptions,
    events: pd.DataFrame | None = None,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    if events is None:
        events = load_events_for_scores(scores)
    summaries = []
    captured_frames = []
    for policy_name, selected in policy_masks(scores, assumptions).items():
        summary, captured = summarize_policy(
            policy_name, scores, selected, events, assumptions
        )
        summaries.append(summary)
        if not captured.empty:
            captured_frames.append(captured)

    summary_df = pd.DataFrame(summaries)
    captured_all = (
        pd.concat(captured_frames, ignore_index=True)
        if captured_frames
        else pd.DataFrame()
    )
    by_type = summarize_by_type(events, captured_all)
    return summary_df, by_type, captured_all


def run_effectiveness_sensitivity(
    scores: pd.DataFrame,
    alert_review_cost: float,
    rates: tuple[float, ...],
    events: pd.DataFrame,
) -> pd.DataFrame:
    frames = []
    for rate in rates:
        assumptions = PolicyAssumptions(
            alert_review_cost=alert_review_cost,
            intervention_effectiveness=rate,
            effectiveness_sensitivity=rates,
        )
        summary, _, _ = run_backtest(scores, assumptions, events)
        frames.append(summary)
    return pd.concat(frames, ignore_index=True)


def main() -> None:
    args = parse_args()
    sensitivity_rates = tuple(args.effectiveness_sensitivity)
    if args.intervention_effectiveness not in sensitivity_rates:
        sensitivity_rates = tuple(sorted((*sensitivity_rates, args.intervention_effectiveness)))

    assumptions = PolicyAssumptions(
        alert_review_cost=args.alert_cost,
        intervention_effectiveness=args.intervention_effectiveness,
        effectiveness_sensitivity=sensitivity_rates,
    )
    ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)

    scores = load_scores(Path(args.scores_path), args.score_if_missing)
    events = load_events_for_scores(scores)
    summary, by_type, captured = run_backtest(scores, assumptions, events)
    effectiveness_sensitivity = run_effectiveness_sensitivity(
        scores,
        assumptions.alert_review_cost,
        assumptions.effectiveness_sensitivity,
        events,
    )

    summary.to_csv(SUMMARY_PATH, index=False)
    by_type.to_csv(BY_TYPE_PATH, index=False)
    captured.to_csv(CAPTURED_EVENTS_PATH, index=False)
    effectiveness_sensitivity.to_csv(EFFECTIVENESS_SENSITIVITY_PATH, index=False)
    write_report(summary, by_type, scores, assumptions, effectiveness_sensitivity)

    primary = summary[summary["policy"] == "top_10pct_per_facility"].iloc[0]
    print("\nFinancial backtest complete.")
    print(f"  Summary: {SUMMARY_PATH}")
    print(f"  By type: {BY_TYPE_PATH}")
    print(f"  Effectiveness sensitivity: {EFFECTIVENESS_SENSITIVITY_PATH}")
    print(f"  Report: {REPORT_PATH}")
    print(
        "  Primary policy net savings: "
        f"{_fmt_money(primary['estimated_net_savings'])} "
        f"({primary['estimated_roi']:.2f}x ROI)"
    )


if __name__ == "__main__":
    main()
